### ISSUE TITLE
Peer to peer Code review

### ISSUE THREAD

**Issue by pinkmoon25** [ademibowale/my-portfolio#16]
I think it would be more appropriate to use only the placeholder text in the text area element, as it will use the required attribute properly while filling the form.

The whole page looks good and responsive as well, I believe it would be better to make the footer links flex items and place them in center vertically and horizontally as it will give a better structure to the whole page.

I believe it will be better to use margin to have space between divs rather than using a `<br>` tag

I think to will be better to have the heading in the header section inside a single tag and stack the text using a fixed width for the element or by using a `<br>` tag.

**Comment by ademibowale** [comment]
Ok
